# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3530a91f7b75a4f37c6f9e5edd85716e3b9f5333c057d40be01ce8258dc64891971147a680e87ba624f32cbaba60635512305251769f5234ca1409bfe33961fe

test:
  secret_key_base: 993adf3c7174a2dc63bc2fb28de0981259dea295b35e4fa68dda87b465fc12f4b313127ba8c37f0fb815af862a4feadc62bee8a8be96bf5c8ca7c44150eeef83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
